### ISSUE TITLE
Empty project folder

### ISSUE THREAD

**Issue by onurkose** [MrDeerly/vue-timeago3#39]
Hello, I wanted to try this package but when I yarn add it it'll give me empty project folder:

![image](https://user-images.githubusercontent.com/139073/144763991-f04eb30b-26dd-4bfe-9c98-007aef6ea5d1.png)

**Comment by MrDeerly** [comment]
Hey @onurkose,

thanks for reporting this! There was an issue with the release workflow, where the package was published before building.. I revoked the broken version (v2.1.1) and created a new release (v2.1.2). You should be able to use the package now! 

Again thanks, and sorry :)
