### ISSUE TITLE
app.config.globalProperties undefined

### ISSUE THREAD

**Issue by ipearx** [MrDeerly/vue-timeago3#575]
Hi I'm trying to use vue-timeago3 with Vue.

After following the install instructions I am given an error:
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'app.config.globalProperties')

I'm using vue 3.2.31, vite 4.0, and bun to install everything. Chances are I'm doing something stupid...

My app.js:

```
import './bootstrap';
import '../css/map.css';

import { createApp, h } from 'vue';
import App from './MapPages/MapLayout.vue';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';

import timeago from 'vue-timeago3' // import timeago

const timeagoOptions = {
  converterOptions: {
      includeSeconds: true,
  }
}

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

const app = createApp(App)
app.use(timeago);
app.use(pinia);
app.mount("#app");
```

And parts of my vue component:

```
<script setup>
import { ref } from 'vue';
import { settingsStore } from "@/stores/SettingsStore.js";
...
import timeago from 'vue-timeago3'

defineEmits(['close']);

</script>

<template>
...
<timeago :datetime="point.stamp" auto-update />
...
</template>
```

**Comment by MrDeerly** [comment]
Hey, thanks for the report!

Can you share the whole error string with me?

Also, in your example `timeagoOptions` is not used. Is this desired or different in your app?

**Comment by ipearx** [comment]
Hi that was the entire error displayed in the console i.e:
"Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'app.config.globalProperties')"

I tried many variations for declaring timeagoOptions both declared globally and in the component, all resulted in the same error. If I removed the timeago tag from the template, the error went away if that helps.

Sorry I don't have the code any more, I ended up writing a wrapper around javascript-time-ago

**Comment by ipearx** [comment]
Sorry forgot to mention, I did use the options like given in the example here https://mrdeerly.github.io/vue-timeago3/guide/configuration.html#example-1
with the same result.

**Comment by MrDeerly** [comment]
Hey @ipearx, sorry for not getting back to you earlier.

After looking at the code you provided again i found that you tried to register the plugin in the component itself (again), which leads to the error. (`import timeago from 'vue-timeago3'`)

Removing that line and registering the plugin in your main.js only should definitly solve your issue.

**Comment by ipearx** [comment]
Thanks for that, hopefully it'll help the next person!
