### ISSUE TITLE
Types missing

### ISSUE THREAD

**Issue by janvorisek** [MrDeerly/vue-timeago3#576]
Thank you for an awesome library, but there are no types distributed on npm.

[See npm sources](https://www.npmjs.com/package/vue-timeago3?activeTab=code)

In package json, there ar types specified in `dist_types` directory which is clearly missing.

**Comment by MrDeerly** [comment]
Hey @janvorisek, thank you very much for bringing up this issue!

The fix was just merged and will be released very soon.

**Comment by MrDeerly** [comment]
Hey! v2.3.2 was just released
